#!/bin/bash

set -e

echo "Running qemu-system-riscv64..."

mkdir -p hda-contents/EFI/BOOT

cp ./BOOTRISCV64.EFI hda-contents/EFI/BOOT/

PFLASH0="./firmware/RISCV_VIRT_CODE.fd"
PFLASH1="./firmware/RISCV_VIRT_VARS.fd"

qemu-system-riscv64 \
    -M virt,pflash0=pflash0,pflash1=pflash1,acpi=off,aclint=on \
    -m 4G -smp 4 -nographic \
    -blockdev node-name=pflash0,driver=file,read-only=on,filename=${PFLASH0} \
    -blockdev node-name=pflash1,driver=file,filename=${PFLASH1} \
    -hda fat:rw:hda-contents